sudo: required
services:
  - docker
language: node_js
node_js:
  - "6.0"
before_install:
  - echo $TRIGGER_REPO
  - echo $CUC_TAG
  # Set Ruby version
  - rvm use --install --default --binary ruby-2.3.1
  # Install chrome & chromium
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update && sudo apt-get install -y google-chrome-stable
  # Install xvfb
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  # Install chrome & chromium
  - sudo apt-get update && sudo apt-get install -y awscli
  # Install chrome & chromium
  - sudo apt-get update && sudo apt-get install -y chromium-bsu
  # Install UI test requirements
#  - npm install -g protractor@3.3.0 grunt-cli
#  - webdriver-manager update # --versions.chrome 2.21
  # Update Node UI test dependencies
#  - npm install
  # Update Ruby cucumber dependencies
  - cd DataSetup
  - gem install bundler
  - bundle install
  # Version reporting
  - ruby -v
  - bundle --version
  - gem --version
  # Run Delete Script to empty DynamoDB before tests start
#  - ./dynamo_delete_script.rb -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -e 'https://dynamodb.us-east-1.amazonaws.com' -r us-east-1
  # Load sample control seed data
#  - ./dynamo_data_upload.rb -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -e 'https://dynamodb.us-east-1.amazonaws.com' -r us-east-1
  - cd ..
  # Reset ECOG Mock service Data
  - curl -X POST "http://pedmatch-uat.nci.nih.gov:3000/restart" -d ''

script:
  # Install xvfb
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - sleep 3 # give xvfb some time to start

  # Run End-to-END tests
   - protractor config.js

  # Generate html report
   - node support/generate_report.js
   - cd ..
   - ls -alt
after_script:
  #Set above, - export DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
  - export DATE_TRIM=`TZ=America/New_York date "+%m-%d-%y"`
  #Upload Reports to S3
  - aws s3 cp ~/build/CBIIT/nci-uMatch-uattests/results/cucumber_report.html s3://cucumber-reports/$DATE_TRIM/End-to-End_tests.html --region us-east-1
  - aws s3 cp ~/build/CBIIT/nci-uMatch-uattests/results/screenshot s3://cucumber-reports/$DATE_TRIM/screenshot --region us-east-1 --recursive

notifications:
  slack: clinicalbiomed:gRp5LqKElNOjUUMPLlq4qC1j
  template:
          - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} %{result} in %{duration} %{commit_message}"
